from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent

from .experiments import REPO_ROOT, get_experiment, list_experiments
from .runner import ExperimentRunner


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="qmanip",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=dedent(
            """
            Curated entrypoint for the Q-Manipulation reward-transfer experiments.

            Examples
            --------
            python run_experiments.py list
            python run_experiments.py show dollar-euro
            python run_experiments.py run dollar-euro --stage all --start 0 --end 30
            python run_experiments.py run autogenerated-linear --stage aggregate
            """
        ).strip(),
    )

    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("list", help="List curated experiments.")

    show_parser = subparsers.add_parser("show", help="Describe one experiment.")
    show_parser.add_argument("experiment", help="Experiment slug shown by the list command.")

    run_parser = subparsers.add_parser("run", help="Run collect, aggregate, plot, or all stages.")
    run_parser.add_argument("experiment", help="Experiment slug shown by the list command.")
    run_parser.add_argument(
        "--stage",
        choices=("collect", "aggregate", "plot", "all"),
        default="all",
        help="Which part of the pipeline to run.",
    )
    run_parser.add_argument("--start", type=int, default=0, help="Inclusive seed index.")
    run_parser.add_argument("--end", type=int, default=30, help="Exclusive seed index.")
    run_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the commands without executing them.",
    )

    return parser


def _print_experiment_summary(experiment_slug: str) -> None:
    experiment = get_experiment(experiment_slug)
    print(f"{experiment.slug}: {experiment.title}")
    print(f"  section: {experiment.paper_section}")
    print(f"  workdir: {experiment.workdir_path}")
    print(f"  summary: {experiment.description}")
    print("  collect:")
    for step in experiment.collect_steps:
        mode = "per-seed" if step.per_seed else "single-run"
        step_workdir = REPO_ROOT / step.workdir if step.workdir else experiment.workdir_path
        extra = ""
        if step_workdir != experiment.workdir_path:
            extra = f", workdir={step_workdir}"
        print(f"    - {step.name}: {step.script_name} ({mode}{extra})")
    print("  aggregate outputs:")
    for spec in experiment.aggregate_specs:
        source_dir = REPO_ROOT / spec.source_workdir if spec.source_workdir else experiment.workdir_path
        output_dir = REPO_ROOT / spec.output_workdir if spec.output_workdir else experiment.workdir_path
        source_pattern = source_dir / Path(spec.input_template)
        print(f"    - {output_dir / spec.output_name} <- {source_pattern}")
    print(f"  plot: {experiment.plot_script or 'None'}")
    if experiment.notes:
        print("  notes:")
        for note in experiment.notes:
            print(f"    - {note}")


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "list":
        for experiment in list_experiments():
            print(f"{experiment.slug:24} {experiment.paper_section:12} {experiment.title}")
        return 0

    if args.command == "show":
        _print_experiment_summary(args.experiment)
        return 0

    if args.command == "run":
        experiment = get_experiment(args.experiment)
        runner = ExperimentRunner(dry_run=args.dry_run)
        runner.run(experiment=experiment, stage=args.stage, start=args.start, end=args.end)
        return 0

    parser.error(f"Unsupported command: {args.command}")
    return 2
