import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sns.set_style("darkgrid")

# -------------------------------------------------------------------------
#   Your confidence interval function (UNCHANGED)
# -------------------------------------------------------------------------
def confidence_interval(data, confidence=0.95):
    n = len(data)
    if n < 2:
        return 0
    m = np.mean(data)
    se = stats.sem(data)
    h = se * stats.t.ppf((1 + confidence) / 2., n - 1)
    return h


# -------------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------------
def smooth(arr, w):
    return np.convolve(arr, np.ones(w), "valid") / w

step = 4           # REQUIRED
max_len = 1600     # REQUIRED


# -------------------------------------------------------------------------
# Panel 1 + 2 Plotter
# -------------------------------------------------------------------------
def plot_behavior_panel(ax, prefix, title):
    arr_star = np.load(f"avg_returns_Q_{prefix}_star.npy")[:, :max_len]
    arr_og   = np.load(f"avg_returns_Q_{prefix}_og.npy")[:, :max_len]
    arr_mu   = np.load(f"avg_returns_Q_{prefix}_mu.npy")[:, :max_len]

    datasets = [
        ("Q* (epsilon-greedy)",           arr_star, "#1f77b4"),
        ("Q* (modified epsilon-greedy)",  arr_og,   "#2ca02c"),
        ("Q_mu (modified epsilon-greedy)",arr_mu,   "#d62728")
    ]

    w = 90  # smoothing window

    for label, data, color in datasets:
        mean = data.mean(axis=0)
        ci = np.array([confidence_interval(data[:, t]) for t in range(data.shape[1])])

        mean_s  = smooth(mean, w)
        upper_s = smooth(mean + ci, w)
        lower_s = smooth(mean - ci, w)

        x = np.arange(len(mean_s)) * step

        ax.plot(x, mean_s, lw=2, color=color, label=label)
        ax.fill_between(x, lower_s, upper_s, color=color, alpha=0.25)

    ax.set_title(title, fontsize=20)
    ax.set_xlabel("Step", fontsize=18)
    ax.set_ylabel("Average Return", fontsize=18)
    ax.tick_params(labelsize=16)
    ax.legend(fontsize=16)


# -------------------------------------------------------------------------
# Panel 3 Plotter (CSV files)
# -------------------------------------------------------------------------
def plot_sbf_panel(ax):
    files = {
        "Q-M (Q-M$_p$)":      "ours_0_3_new.csv",
        "M-Q-M":    r"D:\TMLR 2025\Exp 2 Randomized MDP fixed R\Autogenerated_135\ours_0_3.csv",
        "QL":       "QL_0_3.csv",
        "SFQL":     "SFQL_0_3.csv",
        "SQB":      "clipped-QL_0_3.csv",
        "M-Q-M$_p$":  "ours_0_3.csv",
    }

    colors = {
        "Q-M (Q-M$_p$)":      "#696969",
        "M-Q-M":    plt.cm.tab10(0),
        "QL":       "#ff7f0e",
        "SFQL":     "#2ca02c",
        "SQB":      "#d62728",
        "M-Q-M$_p$":  "#9467bd",
    }

    w = 150

    for label, path in files.items():
        df = pd.read_csv(path)
        if "Unnamed: 0" in df.columns:
            df = df.drop(columns=["Unnamed: 0"])

        data = df.to_numpy()[:, :2000]

        mean = data.mean(axis=0)
        ci   = np.array([confidence_interval(data[:, t]) for t in range(data.shape[1])])

        mean_s  = smooth(mean, w)
        upper_s = smooth(mean + ci, w)
        lower_s = smooth(mean - ci, w)

        x = np.arange(len(mean_s)) * step

        # ax.plot(x, mean_s, lw=2, color=colors[label], label=label)
        if label == "M-Q-M$_p$":
            ax.plot(x, mean_s, lw=2, color=colors[label], label=label, linestyle="--")
        else:
            ax.plot(x, mean_s, lw=2, color=colors[label], label=label)

        ax.fill_between(x, lower_s, upper_s, alpha=0.25, color=colors[label])

    ax.set_title("SBF = 3", fontsize=20)
    ax.set_xlabel("Step", fontsize=18)
    ax.tick_params(labelsize=16)
    ax.legend(fontsize=16)


# -------------------------------------------------------------------------
# Build the 1×3 figure
# -------------------------------------------------------------------------
fig, axs = plt.subplots(1, 3, figsize=(22, 6))

plot_behavior_panel(axs[0], prefix=1, title="Behavior 1")
plot_behavior_panel(axs[1], prefix=2, title="Behavior 2")
plot_sbf_panel(axs[2])

plt.tight_layout()
plt.savefig("Aggregated_Realistic_Comparisonp.jpeg", dpi=450, bbox_inches="tight")
plt.show()
